# This is a basic workflow to help you get started with Actions

name: Kotlin compiler

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build kotlin compiler
        working-directory: ./proteus-compiler-kotlin
        run: gradle clean build
      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          if-no-files-found: error
          path: ./proteus-compiler-kotlin/build/reports/tests/test/index.html



